### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by DenissePerez** [aylliote/senti-py#1]
Hi, I've installed the package, but when importing it, I get the following error 
"SyntaxError: can not delete variable 'mask' referenced in nested scope"

the only command I have in the python file is:
from classifier import *

I'd appreciate your help with this.

**Comment by DenissePerez** [comment]
I just noticed I was using python 2.7

**Comment by aylliote** [comment]
I apologize for the slow reply, I didn't get the notifications.
I wrote the code with python 3 so there must be some troubles if you run it with python 2 indeed.
Could you save your issue ?
